apiVersion: v1
kind: Pod
metadata:
  labels:
    run: giropops 
  name: giropops
spec:
  containers:
  - image: nginx 
    name: webserver
    volumeMounts:
    - mountPath: /giropops    # volume sera montado aqui no /giropops
      name: primeiro-emptydir  # volume que foi criado la em baixo 
    resources:
      limits:
        cpu: "1"  # maximo permitido para esse container      
        memory: "128Mi" # maximo permitido   
      requests:      
        cpu: "0.5"  # ja sobe o container com 0.3 reservado para esse container 
        memory: "64Mi" # ja sobe com essa reserva 
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:                     # criaçao do volume 
  - name: primeiro-emptydir    # nome do volume criado 
    emptyDir:                  # tipo do volume - inicia vazio 
      sizeLimit: 256Mi         # tamanho maximo 
