apiVersion: v1
kind: Pod
metadata:
  labels:
    run: girus
  name: girus
spec:
  containers:
  - image: nginx
    name: nginx
    resources: {}
  - image: busybox
    name: busybox 
    args:    # argumentos 
    - sleep  # para esperar 
    - "600"  # 600s   
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
